# Generated by Django 4.2.30 on 2026-09-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
